### ISSUE TITLE
Mobs spawn too often and changing the config does nothing.

### ISSUE THREAD

**Issue by Toucandi** [Blaez-Dev/RWBYM-2.0#13]
I'm on the latest version, 3.6.1, and i can barely leave my house without getting overwhelmed with mobs. I went into the config to set all the spawn rates lower, and I relaunch my game to see that they still spawn just as often. Then I set them all to 0, and they're still there. I even set them to 90 to see if it went the other way around, and they didn't spawn any differently. Not sure if this is something I'm doing wrong or if the config is messed up.

**Comment by Blaez-Dev** [comment]
The Spawn-rate in config is Spawn-weight it can only be lowered so much, if you want to reduce the spawn rates further you'd need to download a mod to change mob caps or individual spawnrates as there is only so much you can influence it due to way vanilla spawns mobs. I'm sorry I can't offer more help
