### ISSUE TITLE
Aiming with Aquae Alatl

### ISSUE THREAD

**Issue by DrCrowller** [Blaez-Dev/RWBYM-2.0#19]
The aiming with the bow mod of Aquae Alatl is wrong, as the arrow sometimes just go 30° different from the view.
Maybe a vector problem?
The fals aiming is recurrent (not an isolated case) and is very problematic.

**Comment by Blaez-Dev** [comment]
I'm chasing it down now, however its seems its unintentional. it might appear odd however, the arrow fly's normally. the grouping for medium distance ((which is a bows use case as bows are alot less accurate then a gun for obvious reasons)) seems to just be a rendering problem which has been the case since the mods first release. its not something I understand how to fix as far as that goes however the arrows fly where you are pointed even if it seems to render oddly. if you can provide a video to show more closely the issue that would be appreciated. if not I'll have to consider this issue closed as theres nothing I can do to fix it I don't think.

**Comment by DrCrowller** [comment]
I will send this asap.
Before sunday.
