### ISSUE TITLE
Rapiers issue with other mods

### ISSUE THREAD

**Issue by CmdrJane** [Blaez-Dev/RWBYM-2.0#20]
Rapiers doing some unresonable amount of damage to some moded mobs. I guess this is special trait of its kind of weapons, but all rapiers has 3 atk speed and doing like double damage. For example dragons from Ice and Fire mod get melted in seconds. 

Video: https://youtu.be/qexOn1QUUvc

Its also have weird outcome of damage when Animus mod installed. But there im not sure which one is the problem. https://www.curseforge.com/minecraft/mc-mods/animus/files

And few words about rapiers - 14 damage with this trait and 3 atk speed seems very OP, maybe nerf? And cooldown for Myrtenaster charge is needed

**Comment by Blaez-Dev** [comment]
Rapiers have pierce armour, their damage can not be boosted beyond the double damage if the target is armoured. this is intentional for that class of weapon as is their speed. the weapons are fine as they are. you can perform much better with heavier hitting weapons and the right semblance. the rapiers are a solid option for taking on single targets but are weak to groups.

**Comment by CmdrJane** [comment]
okay then, so can i ask what nora and jaune semblance doing?

**Comment by Blaez-Dev** [comment]
Noras requires the player to be hit by lightning dust bullets or to have a lightning dust gem in the offhand to trigger.  strength and speed jaunes is to transfer aura to others however his aura has the benefit of doubling the base aura that the player has and receives from leveling which makes it useful for tanking and other stuff like aura based weapons.
