### ISSUE TITLE
Biome Bundle Incompatibility

### ISSUE THREAD

**Issue by Pengu-Hunter** [Blaez-Dev/RWBYM-2.0#25]
If you load Rwbym and biome bundle then Rwbym's biomes don't seem to generate.

**Comment by Blaez-Dev** [comment]
its possible that there are too many biomes added by biome bundle making them very rare. please load your game using nature's compass and try locating the biomes this way to ensure it is not that. as it shouldn't be a incompatibility unless biome bundle specifically disables any other biomes from spawning entirely and even then this might be more a issue to approach them with rather then us as we're using the standard methods to add biomes so if there is any wierdness it would come from a incompatibility that they themselves created.

**Comment by Pengu-Hunter** [comment]
I tried your suggestion and the compass can still see your mods biomes but can seem to find them in the radius that it checks so i don't know if that means that your biomes have been made stupid rare by Biome bundle or disabled altogether so I'll consider this end closed and try biome bundle for a solution thanks for the prompt response.

**Comment by Blaez-Dev** [comment]
its likely not their fault then, its just there's so many biomes that it makes it hard to find a specific one. what you can do is modify the weight of the biomes inside the rwbym config and increase them.. restart your game and make a new world or generate new chunks. because I accounted for that issue already. I'm glad you enjoy the mod, and took the time to open a issue. I'm going to leave this issue open incase you need any further assistance. if however it can't find them at all then it might actually be their issue. try increasing the weights if thats the case and if its still having issues raise the issue with biome bundle.

**Comment by Pengu-Hunter** [comment]
I found an older Biome bundle issue where someone had trouble with biomes added by mods other than biome bundle and the tl;dr of the response was the biome bundle is incompatible with any mods that add biomes.
