### ISSUE TITLE
Epic Fight Mod switches RWBYM weapons to wrong hand.

### ISSUE THREAD

**Issue by shadowbolt79** [Blaez-Dev/RWBYM-2.0#35]
So I'm not expecting the custom armor models to work with this mod, though most armors still work just fine, but this issue with weapons threw me.

Every single weapon from the RWBY mod gets thrown into the offhand, which messes with the animations that would have been a wonderful combination with this mod. Otherwise, everything seems to still function correctly.

I have yet to find any other mods that EFM has this issue with, which is why I'm also posting this here.

Forge 14.23.5.2847
Epic Fight Mod 2.2.4
RWBYM 4.6.7

**Comment by Blaez-Dev** [comment]
this would be something that Epic fight would have to fix since they have their own way of handling things. if it only happens with our mod. it might be because we have our weapons count as bows; so if you can change the settings for that as to which hand it prioritizes here then that would fix it. however there's nothing I can do about this issue.

**Comment by shadowbolt79** [comment]
I have passed that information on to the EFM dev. Hopefully they can fix it, because there's no hand settings, just weapon types, and I had already set that. Thanks!
